app_name = "hello"
app_env = "local"
app_addr = "127.0.0.1:8100"


[apollo]
server = "http://127.0.0.1:8100/apollo"
cluster = "default"
appid = "appid-demo"
namespace = "100.go-service,app.json,application"
log = "./logs/apollo.log"

[database.default]
driver = "mysql"
connection = "root:root@127.0.0.1/test?charset=utf8mb4&parseTime=true&loc=Local"
prefix = "test_"
log_level = 4
console_log = true

[database.default.pool]
max_idle_conns = 20
max_open_conns = 60
conn_max_lifetime = "1s"

[redis.default]
addr = "127.0.0.1:6379"
db = 6
password = ""
prefix = "partner:"

#MQ信息
[mq]
endpoint = "http://127.0.0.1:90899"
access_key_id = "KSJKHDKHJD10010010"
access_key_secret = "FxX0002341WJ03434343hKT"
instance_id = "MQ_INST_193989199390_VjmhHdQ"


