app_name = "hello"
app_env = "local"
app_addr = "127.0.0.1:8100"


[apollo]
enable = true #是否启用Apollo配置
server = "http://test-apollo.weimiaocaishang.com"
cluster = "default" # 集群
appId = "cq-partner-api" #appId
namespaces = "100.go-service app.json application" # 命名空间
secret = "" # 安全模式下客户端需要的访问密钥
isBackupConfig = true # 是否从备份区获取配置。默认为false
backupConfigPath = "./tmp" # 备份配置文件路径
syncServerTimeout=10 # 同步配置服务的超时时间,默认为10秒


[database.default]
driver = "mysql"
connection = "root:root@127.0.0.1/test?charset=utf8mb4&parseTime=true&loc=Local"
prefix = "test_"
log_level = 4
console_log = true

[database.default.pool]
max_idle_conns = 20
max_open_conns = 60
conn_max_lifetime = "1s"

[redis.default]
addr = "127.0.0.1:6379"
db = 6
password = ""
prefix = "partner:"

#MQ信息
[mq]
endpoint = "http://127.0.0.1:90899"
access_key_id = "KSJKHDKHJD10010010"
access_key_secret = "FxX0002341WJ03434343hKT"
instance_id = "MQ_INST_193989199390_VjmhHdQ"


